### ISSUE TITLE
Will not save settings, reverting back to Step 2

### ISSUE THREAD

**Issue by audvin** [erayalakese/slack-wordpress#10]
I'm selecing the notifications I want and to which channels they are sent, but after selecting Submit I'm back to Step 2. 

I see this message on top of the page: Warning: array_merge(): Argument #1 is not an array in /wp-content/plugins/slack-integration/inc/plugin.class.php on line 38

short_open_tag is On

**Comment by erayalakese** [comment]
@audvin 

Can you please try again by browsing to Slack admin page with this url : [http://YOURDOMAIN/wp-admin/options-general.php?page=slack-for-wordpress](http://localhost/slack-wordpress/wp-admin/options-general.php?page=slack-for-wordpress) ?

And do you have any channels and groups in your Slack account ?

**Comment by audvin** [comment]
Visited that url, it put me back to the Step 2 button. From which I go through the authentication etc. then after Save back to the same url/page and Step 2.

Yes, have channels in my team account.

**Comment by erayalakese** [comment]
@audvin ,

I'm working on it . Please follow this issue post for updates. Thank you.

**Comment by erayalakese** [comment]
@audvin Can you please try this version : https://github.com/erayalakese/slack-wordpress/archive/master.zip

**Comment by audvin** [comment]
That worked, thanks!
