### ISSUE TITLE
Feature request: Custom post types

### ISSUE THREAD

**Issue by audvin** [erayalakese/slack-wordpress#11]
Hi,

I'm really enjoying this plugin! My only feature request would be support for custom post types. Is that in the works?

**Comment by erayalakese** [comment]
Hello @audvin ,

Thanks for idea. CPT support is in my mind , but I just need some time for it. I'm a little busy nowadays. So I'll note it for next release.

**Comment by audvin** [comment]
Awesome, thanks!

**Comment by erayalakese** [comment]
Feature added at v1.5.0

**Comment by audvin** [comment]
Thanks for this, it works great so far :+1:
