### ISSUE TITLE
After install, error massage appear in setting menu, slack page 

### ISSUE THREAD

**Issue by dialektike** [erayalakese/slack-wordpress#15]
Warning: file_get_contents() [function.file-get-contents]: URL file-access is disabled in the server configuration in /home/hosting_users/malgunlonly/www/wp-content/plugins/slack-integration/inc/api.class.php on line 37

Warning: file_get_contents(https://slack.com/api/channels.list?exclude_archived=1&token=) [function.file-get-contents]: failed to open stream: no suitable wrapper could be found in /home/hosting_users/malgunlonly/www/wp-content/plugins/slack-integration/inc/api.class.php on line 37

Warning: file_get_contents() [function.file-get-contents]: URL file-access is disabled in the server configuration in /home/hosting_users/malgunlonly/www/wp-content/plugins/slack-integration/inc/api.class.php on line 50

Warning: file_get_contents(https://slack.com/api/groups.list?exclude_archived=1&token=) [function.file-get-contents]: failed to open stream: no suitable wrapper could be found in /home/hosting_users/malgunlonly/www/wp-content/plugins/slack-integration/inc/api.class.php on line 50

**Comment by erayalakese** [comment]
Because 'file_get_contents()' function is disabled in your server configs.
I'll write a cURL wrapper for this.
13 May 2015 11:01 tarihinde "Dialektike" notifications@github.com yazdı:

**Comment by erayalakese** [comment]
This commit will solve your problem 90ef8d1781d823193e50b9a1bc1862b17b7d2148 @dialektike  
It will be included in next release.
