### ISSUE TITLE
Feature request: include excerpt in notifications

### ISSUE THREAD

**Issue by jphorn** [erayalakese/slack-wordpress#16]
Really want to switch to this plugin, but we need to have the excerpt in the notification, similar to what the (more limited) plugin we currently use has.

https://github.com/gedex/wp-slack/issues/15

**Comment by erayalakese** [comment]
@jphorn v1.6.0 will be released after some tests.

Thank you.

**Comment by jphorn** [comment]
And thank you for the quick addition!

**Comment by erayalakese** [comment]
v1.6.0 released.
