### ISSUE TITLE
Interfering with Jetpack Activation.

### ISSUE THREAD

**Issue by wormeyman** [erayalakese/slack-wordpress#18]
On a new site i activated slack-wordpress first and then i tried to activate jetpack but every time jetpack returned me to my site it took me to the slack-wordpress settings instead. De-activating slack-wordpress allowed me to activate jetpack.

**Comment by erayalakese** [comment]
@wormeyman Thank you for report. Bug solved in v1.6.1 you can download it from [here](https://github.com/erayalakese/slack-wordpress/archive/v1.6.1.zip). Or wait for WordPress.org release.
