### ISSUE TITLE
When a user logged in

### ISSUE THREAD

**Issue by jaisonn** [erayalakese/slack-wordpress#19]
It would be awesome to get a live feed when a user logged in. I have a lot of wordpress websites and I would like to understand when people logged in.

**Comment by cvladan** [comment]
Same for me

**Comment by erayalakese** [comment]
![image](https://cloud.githubusercontent.com/assets/782514/8535193/2af13d40-244c-11e5-8d7c-3bb53dc13f68.png)

@jaisonn and @cvladan  Thank you for your feature request. It just implemented to new version of Slack. It will be released soon.
