### ISSUE TITLE
PHP Errors after installing plugin

### ISSUE THREAD

**Issue by metagard** [erayalakese/slack-wordpress#26]
Hi,

I just installed the plugin and I am getting the following errors:

On every wordpress dashboard page:

Notice: Undefined index: page in /path/plugin.class.php on line 585

On the plugin settings page:

Notice: Trying to get property of non-object in /path/plugin.class.php on line 85
Notice: Undefined index: unlink in /path/plugin.class.php on line 596
Notice: Undefined index: slack_options_submit in /path/plugin.class.php on line 602
Notice: Undefined index: app_client_id in /path/plugin.class.php on line 606

If it helps, the server is running PHP 5.4.40 .

Thanks!

**Comment by erayalakese** [comment]
Hello @metagard ,

Thank you for your feedback. These warnings are solved in v1.7.1 and published. You will get update soon.
