### ISSUE TITLE
short_open_tag must be enable.

### ISSUE THREAD

**Issue by likol** [erayalakese/slack-wordpress#3]
Hi ,erayalakese

you use the short tag of php on this project, but you not mention it.
maybe you want add this to README or just change short tag to normal tag :D

however, it's still good work! thanks :p

Regards.

**Comment by erayalakese** [comment]
@likol Thank you for your suggestion. You're right, short tags must be enabled because I'm using shorthand way of _echo_ and _if_ . 

I'll mention it in Readme file.
