### ISSUE TITLE
Could we please get a notification on new subscribers?

### ISSUE THREAD

**Issue by materemias** [erayalakese/slack-wordpress#7]
I would like to get posted about new subscribers, would you make it possible?

**Comment by erayalakese** [comment]
You mean RSS subscribers,  right?  @ratson

**Comment by materemias** [comment]
I mean people who appear under page wp-admin/admin.php?page=subscribers I believe this is not a plugin functionality but default. these guys don't appear under regular users
--update
I now found out it is a custom functtion programmed in the site template, could you give advice how i could add a custom hook to it?

**Comment by erayalakese** [comment]
Hello @ratson, 

As you find out it's 3th party plugin/service. I will provide a method for plugin/theme developers and release it in a day. Please follow this issue. 

For a quick (and **untested**)  resolution : try using publish_post($channel, $msg) method inside Slack_API class.  You can reach this class with Plugin class' getApi() method. 

Thank you.

**Comment by materemias** [comment]
HI,

thanks for the quick update, I am looking forward to see the guide, at the same time would it be possible to post messages to private groups?

rm

**Comment by erayalakese** [comment]
@ratson  ,

Can you please update your plugin to v1.2.0 by [downloading this](https://github.com/erayalakese/slack-wordpress/archive/v1.2.0.zip) (just `git pull` if you download plugin with **git**) and then follow **For Developers** section of Readme.md ?

**Comment by materemias** [comment]
I'll definitely do so, can I post to private groups too? That's a must for our use case...

**Comment by erayalakese** [comment]
@ratson  ,

Sorry it's my mistake, I totally forgot about it. Just give me an hour.

**Comment by materemias** [comment]
thank you @erayalakese i truly appreciate this!

**Comment by erayalakese** [comment]
@ratson 

It will be released as v1.3.0 in a few minutes. Thank you.

**Comment by materemias** [comment]
great, thank you!

**Comment by materemias** [comment]
$wpps_plugin->getApi()->publish_post($channel_to_post, $msg); seems to stop execution. what could have gone wrong?

**Comment by erayalakese** [comment]
@ratson it was just a typo and I fixed it immediately yesterday. You should use $slack_plugin instead of $wpps_plugin.  Check readme file for example. 

And please vote / review the plugin on [Wordpress.org](https://wordpress.org/plugins/slack-integration/)

Thank you.

**Comment by materemias** [comment]
and it works! thanks

**Comment by materemias** [comment]
I registered just to post a rating ;)

**Comment by erayalakese** [comment]
Wow,  thank you :) @ratson

**Comment by materemias** [comment]
well deserved!
